apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-secret
spec:
  secretStoreRef:            # Secret을 가져올 SecretStore 작성
    name: aws-secretmanager
    kind: SecretStore
  refreshInterval: 1h
  target:
    name: redis-cluster   # 가져온 값으로 클러스터에 생성할 Secret object의 이름
  data:
    - secretKey: redis-password
      remoteRef:             # Secrets Manager에 저장된 Secret
        key: my-eks-secret
        property: redis-password