apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:      # IRSA 연결한 ServiceAccount
            name: redis-cluster-sa